# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-28 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='to_do_list_value',
            field=models.TextField(default=''),
        ),
    ]
